---
title: "Thesis"
author: "Thy Nguyen"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE, }
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```


```{r}
setwd("../depression-network-model/analysis")
df <- read.csv("../results/simulated_data_baseline.csv")
```

# Explanotory analysis

```{r message=FALSE, warning=FALSE}
library(dplyr)
summary(df)
sd <- apply(df, 2, sd)
print(sd)
```

```{r}
library(ggplot2)
se <- function(x) sd(x) / sqrt(length(x))
mean_mfq_10ep <- df %>% group_by(episode_number) %>% summarise(
  avg_mfq_without = mean(mfq_without_network),
  avg_mfq_with = mean(mfq_with_network),
  lower_CI_with = mean(mfq_with_network) - 1.96 * se(mfq_with_network),
  upper_CI_with = mean(mfq_with_network) + 1.96 * se(mfq_with_network)
)
```

```{r}
id_21 <- df %>% filter(network_id == 21)

plot21 <- ggplot(id_21, aes(x = episode_number)) +
  geom_line(aes(y = mfq_without_network, color = "Without social support")) +
  geom_line(aes(y = mfq_with_network, color = "With social support")) +
  geom_hline(yintercept = 28, color = "red", linetype = "dashed") +
  geom_text(aes(y = mfq_without_network, label = round(mfq_without_network, 1)), vjust = -0.5, color = "black") +
  geom_text(aes(y = mfq_with_network, label = round(mfq_with_network, 1)), vjust = 1.5, color = "deepskyblue") +
  scale_x_continuous(limits = c(0, 10), breaks = 0:10) +
  scale_y_continuous(breaks = c(28, pretty(id_21$mfq_without_network), pretty(id_21$mfq_with_network))) +
  xlab("Episode") +
  ylab("MFQ") +
  scale_color_manual(
    name = "Condition",
    values = c(
      "Without social support" = "black",
      "With social support" = "deepskyblue"
    )
  ) +
  theme_classic() +
  theme(legend.position = "right")
plot21
ggsave("id_21-0.01.png", plot = plot21, units = "in", width = 7, height = 4.5, dpi = 300)
```

```{r}
plot <- ggplot(mean_mfq_10ep, aes(x = episode_number)) +
  geom_ribbon(
    aes(ymin = lower_CI_with, ymax = upper_CI_with),
    fill = "deepskyblue2",
    alpha = 0.2
  ) +
  geom_line(aes(y = avg_mfq_without, color = "Without social support")) +
  geom_line(aes(y = avg_mfq_with, color = "With social support")) +
  geom_text(aes(y =avg_mfq_without, label = round(avg_mfq_without, 1)), vjust = -0.5, color = "black") +
  geom_text(aes(y = avg_mfq_with, label = round(avg_mfq_with, 1)), vjust = 1.5, color = "deepskyblue") +
  scale_x_continuous(limits = c(0,10), breaks = 0:10) +
  xlab("Episode") +
  ylab("MFQ") +
  scale_color_manual(
    name = "Condition",
    values = c(
      "Without social support" = "black",
      "With social support" = "deepskyblue"
    )
  ) +
  theme_classic() +
  theme(legend.position = "right")
plot

ggsave("mfq-comparison.png", plot = plot, units = "in", width = 7, height = 4.5, dpi = 300)
```

```{r}
df <- read.csv("network_varying_p1.csv")
```

```{r}
p1_ss <- df %>% group_by(p_connection_1) %>% 
  summarise(avg_friend = mean(friend_support), 
            avg_fam = mean(family_support),
            lower_CI_friend = mean(friend_support) - 1.96 * se(friend_support),
            upper_CI_friend = mean(friend_support) + 1.96 * se(friend_support),
            lower_CI_fam = mean(family_support) - 1.96 * se(family_support),
            upper_CI_fam = mean(family_support) + 1.96 * se(family_support),
)

plot <- ggplot(p1_ss, aes(x = p_connection_1)) +
 geom_ribbon(
    aes(ymin = lower_CI_fam, ymax = upper_CI_fam),
    fill = "azure4",
    alpha = 0.2
  ) +
  geom_ribbon(
    aes(ymin = lower_CI_friend, ymax = upper_CI_friend),
    fill = "deepskyblue",
    alpha = 0.2
  ) +
  geom_line(aes(y = avg_fam, color = "Family support")) +
  geom_line(aes(y = avg_friend, color = "Friend support"))+
  xlab("Connection probability of the first layer") +
  ylab("Social support level") +
  geom_text(aes(y = avg_fam, label = round(avg_fam, 1)), vjust = -0.5, color = "black") +
  geom_text(aes(y = avg_friend, label = round(avg_friend, 1)), vjust = -0.5, color = "deepskyblue") +
  scale_color_manual(
    name = "Type of support",
    values = c(
      "Family support" = "black",
      "Friend support" = "deepskyblue"
    )
  ) +
  scale_x_continuous(limits = c(0.15, 0.65), breaks =  seq(0.15, 0.65, by = 0.1))+
  theme_classic() +
  theme(legend.position = "right")
plot
ggsave("varying-p1-ss.png", plot = plot, units = "in", width = 7, height = 5, dpi = 300)
```

```{r}
mean_mfq_10ep <- df %>% group_by(p_connection_1, episode_number) %>% summarise(
  avg_mfq_without = mean(mfq_without_network),
  avg_mfq_with = mean(mfq_with_network),
  lower_CI_with = mean(mfq_with_network) - 1.96 * se(mfq_with_network),
  upper_CI_with = mean(mfq_with_network) + 1.96 * se(mfq_with_network)
)
```

```{r}
# Plot 6 lines
plot1 <- ggplot(mean_mfq_10ep, aes(x = episode_number, color = factor(p_connection_1))) +
  geom_line(aes(y = avg_mfq_with)) +
  scale_x_continuous(limits = c(0,10), breaks = 0:10) +
  xlab("Episode") +
  ylab("MFQ") +
  theme_classic() +
  labs(color = "Connection probability") +
  theme(legend.position = "right")
plot1

ggsave("varying-p1-mfq-lines.png", plot = plot1, units = "in", width = 7, height = 4, dpi = 300)

# Plot 6 facet
custom_labeller <- as_labeller(c(
  `0.15` = "P = 0.15",
  `0.25` = "P = 0.25",
  `0.35` = "P = 0.35",
  `0.45` = "P = 0.45", 
  `0.55` = "P = 0.55",
  `0.65` = "P = 0.65"
))
plot2 <- ggplot(mean_mfq_10ep, aes(x = episode_number)) +
  geom_ribbon(
    aes(ymin = lower_CI_with, ymax = upper_CI_with),
    fill = "deepskyblue2",
    alpha = 0.2
  ) +
  geom_line(aes(y = avg_mfq_without, color = "Without social support")) +
  #geom_point(aes(y = avg_mfq_without, color = "Without social support")) +
  geom_line(aes(y = avg_mfq_with, color = "With social support")) +
  #geom_point(aes(y = avg_mfq_with, color = "With social support")) +
  scale_x_continuous(limits = c(0,10), breaks = 0:10) +
  xlab("Episode") +
  ylab("MFQ") +
  scale_color_manual(
    name = "Condition",
    values = c(
      "Without social support" = "black",
      "With social support" = "deepskyblue"
    )
  ) +
  theme_classic() +
  theme(legend.position = "right", 
        strip.background = element_blank()) +
  facet_wrap(~ p_connection_1, scales = "free_y", labeller = custom_labeller)
plot2
ggsave("varying-p1-mfq-facet.png", plot = plot2, units = "in", width = 9, height = 5, dpi = 300)
```

```{r}
df2 <- read.csv("network_varying_increase_support_level.csv")

mean_mfq_10ep_inc_ss <- df2 %>% group_by(increase_support_level, episode_number) %>% summarise(
  avg_mfq_without = mean(mfq_without_network),
  avg_mfq_with = mean(mfq_with_network),
  lower_CI_with = mean(mfq_with_network) - 1.96 * se(mfq_with_network),
  upper_CI_with = mean(mfq_with_network) + 1.96 * se(mfq_with_network)
)

# Varying-coefficient plot
custom_labeller <- as_labeller(c(
  `0.25` = "delta = 0.25",
  `0.5` = "delta = 0.5",
  `1` = "delta = 1",
  `3` = "delta = 3", 
  `5` = "delta = 5",
  `7` = "delta = 7"
))
plot3 <- ggplot(mean_mfq_10ep_inc_ss, aes(x = episode_number)) +
  geom_ribbon(
    aes(ymin = lower_CI_with, ymax = upper_CI_with),
    fill ="deepskyblue2",
    alpha = 0.2
  ) +
  geom_line(aes(y = avg_mfq_without, color = "Without social support")) +
  geom_line(aes(y = avg_mfq_with, color = "With social support")) +
  scale_x_continuous(limits = c(0, 10), breaks = 0:10) +
  xlab("Episode") +
  ylab("MFQ") +
  scale_color_manual(
    name = "Condition",
    values = c(
      "Without social support" = "black",
      "With social support" = "deepskyblue"
    )
  ) +
 theme_classic() +
  theme(legend.position = "right", 
        strip.background = element_blank()) +
  facet_wrap(~ increase_support_level, scales = "free_y", labeller = custom_labeller)
plot3

ggsave("scaleup-coef.png", plot = plot3, units = "in", width = 9, height = 5, dpi = 300)
```

```{r}
diff_7 <- df2 %>% filter(increase_support_level == 7) %>% 
  group_by(episode_number) %>% 
  summarise(
  avg_mfq_without = mean(mfq_without_network),
  avg_mfq_with = mean(mfq_with_network),
  lower_CI_with = mean(mfq_with_network) - 1.96 * se(mfq_with_network),
  upper_CI_with = mean(mfq_with_network) + 1.96 * se(mfq_with_network)
)

plot4 <- ggplot(diff_7, aes(x = episode_number)) +
  geom_ribbon(
    aes(ymin = lower_CI_with, ymax = upper_CI_with),
    fill = "deepskyblue2",
    alpha = 0.2
  ) +
  geom_line(aes(y = avg_mfq_without, color = "Without social support")) +
  geom_line(aes(y = avg_mfq_with, color = "With social support")) +
  geom_hline(yintercept = 28, color = "red", linetype = "dashed") +
  geom_text(aes(y = avg_mfq_without, label = round(avg_mfq_without, 1)), vjust = -0.5, color = "black") +
  geom_text(aes(y = avg_mfq_with, label = round(avg_mfq_with, 1)), vjust = 1.5, color = "deepskyblue") +
  scale_x_continuous(limits = c(0, 10), breaks = 0:10) +
  scale_y_continuous(breaks = c(28, pretty(diff_7$avg_mfq_without), pretty(diff_7$avg_mfq_with))) +
  xlab("Episode") +
  ylab("MFQ") +
  scale_color_manual(
    name = "Condition",
    values = c(
      "Without social support" = "black",
      "With social support" = "deepskyblue"
    )
  ) +
  theme_classic() +
  theme(legend.position = "right")
plot4
ggsave("scaleup-coef-7.png", plot = plot4, units = "in", width = 7, height = 4.5, dpi = 300)
```